<?php

/**
 * Media_Model_Doctrine_VideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Media_Model_Doctrine_VideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Media_Model_Doctrine_VideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Media_Model_Doctrine_Video');
    }
    
    public function findSortedVideosByIds($ids, $hydrationMode = Doctrine_Core::HYDRATE_RECORD) {
        $q = $this->createQuery('v')
                ->select('v.*')
                ->where('v.id IN ?', array($ids))
                ->orderBy('v.lft ASC')
                ;
        return $q->execute(array(), $hydrationMode);
    }
}