<?php

/**
 * Product_Model_Doctrine_Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product_Model_Doctrine_Category extends Product_Model_Doctrine_BaseCategory
{
   
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function getMetatagId() {
        return $this->_get('metatag_id');    
    }
    
    public function isStatus() {
        return $this->_get('status');
    }
    public function getSlug() {
        return $this->_get('slug');
    }
    
    public function setStatus($status = true) {
        $this->_set('status', $status);
    }
    
    public function getDiscountId() {
        return $this->_get('discount_id');    
    }
    
    public function setDiscountId($discountId) {
        $this->_set('discount_id', $discountId);
    }
    public function setMetatagId($discountId) {
        $this->_set('metatag_id', $discountId);
    }
    
    
    
    public function setUp() {
        $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
            'local' => 'photo_root_id',
            'foreign' => 'id'
        ));
	
	$this->hasMany('Media_Model_Doctrine_Photo as Photos', array(
            'local' => 'photo_root_id',
            'foreign' => 'root_id'
        ));
        
        $this->hasOne('Default_Model_Doctrine_Metatag as Metatags', array(
            'local' => 'metatag_id',
            'foregin' => 'id'
        ));
        parent::setUp();
    }
}