<?php

/**
 * Product_Model_Doctrine_CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_Category');
    }
    
    public function getCategoryQuery() {
        $q = $this->createQuery('a')
                ->addSelect('a.*')
                ->addSelect('tr.*')
                ->addSelect('m.*')
                ->leftJoin('a.Translation tr')
                ->leftJoin('a.Metatags m')
                ;
        return $q;
    }
}