
     <div class="flexslider">
    <ul class="slides">
        
        <li>
            <img src="/assets/media/slides/2.jpg"  alt="img" />
     <div class="flex-caption">
  <h3>SUPER CARS DEALER </h3>
          <p> Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum  Viva mus lobortis consequat purus. Curabitur commodo. Etiam sed nulla</p>  
<a href="http://templines.com/" class="btn btn-main btn-primary btn-lg uppercase" ><span>View Cars</span></a> </div>
        </li>
        <li>
            <img src="/assets/media/slides/3.jpg"  alt="img" />
       <div class="flex-caption">
  <h3>SUPER CARS DEALER </h3>
          <p> Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum  Viva mus lobortis consequat purus. Curabitur commodo. Etiam sed nulla</p>  
<a href="http://templines.com/" class="btn btn-main btn-primary btn-lg uppercase" ><span>View Cars</span></a> </div>
        </li>
    </ul>
</div>

  <script type="text/javascript">

    $(window).load(function(){
		
		$('.flexslider').flexslider({
 			animation: 'fade', 		   //String: Select your animation type, "fade" or "slide"
 			controlNav: true,   	  //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
 			directionNav: true,		 //Boolean: Create navigation for previous/next navigation? (true/false)
 			slideshowSpeed: 7000,   //Integer: Set the speed of the slideshow cycling, in milliseconds
 			animationSpeed: 600,   //Integer: Set the speed of animations, in milliseconds
 			pauseOnHover: false,   //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
 			prevText: "",        //String: Set the text for the "previous" directionNav item
 			nextText: "",		//String: Set the text for the "next" directionNav item
			slideshow: false
 		});

     
    });
  </script>