<?php foreach($this->photos as $photo): ?>
<li class="pull-left">
    <?php if($photo->getOffset()): ?>
    <a id="main_photo" href="/media/photos/<?php echo $photo->getOffset() ?>/<?php echo $photo->getFilename() ?>" rel="prettyPhoto" name="<?php echo $this->offer->get('PhotoRoot')->getTitle() ?>">
        <img src="/media/photos/<?php echo $photo->getOffset() ?>/126x126/<?php echo $photo->getFilename() ?>" data-original="/media/photos/<?php echo $this->offer->get('PhotoRoot')->getOffset() ?>/<?php echo $photo->getFilename() ?>" alt="<?php echo $photo->getTitle() ?>">
    </a>
    <?php else: ?>
    <a id="main_photo" href="/images/gallery/1.jpg" rel="prettyPhoto" name="<?php echo $this->translate('No photo') ?>">
        <img src="/images/gallery/preload.png" data-original="/images/gallery/thumbnails/1.jpg" alt="<?php echo $this->translate('No photo') ?>">
    </a>
    <?php endif; ?>
    <div class="actionBtn">
         <a class="move" href="<?php echo $this->adminUrl('move-offer-photo', 'offer', array('id' => $photo->id, 'move' => 'up', 'offer' => $this->offer->id)) ?>"><span class="icon16 minia-icon-arrow-left white"></span></a>
        <a href="#" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
        <a href="#" class="delete" rel="<?php echo $photo->id; ?>"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
        <a class="move" href="<?php echo $this->adminUrl('move-offer-photo', 'offer', array('id' => $photo->id, 'move' => 'down', 'offer' => $this->offer->id)) ?>"><span class="icon16 minia-icon-arrow-right white"></span></a>
    </div>
</li>
<?php endforeach; ?>

