<script type="text/javascript">
$(document).ready(function() {
   
//    $('#category_id').select2();
    
     $('.section').hide();
     $('.contentSection').show();
     $('.btnList li').click(function(){
        var rel = $(this).attr('rel');
        $('.section').hide();
        $('.'+rel).show();
     });
     
     if($('li[rel="optionsSection"]').find('input')){
	 $('li[rel="optionsSection"]').css('display','none');
     }
});
</script>

<div class="container_12 clearfix leading">
    
    <div class="grid_12">
 
         <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Add '.$this->actionName) ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <ul class="btnList">
                    <li rel="contentSection"><button class="btn" type="button">Treść</button></li>
                    <li rel="optionsSection"><button class="btn" type="button">Opcje</button></li>
                    <li rel="metatagSection"><button class="btn" type="button">Pokaż metatagi</button></li>
                </ul>
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    
                    <span class="section contentSection metatagSection">
                        <div class="page-header">
                            <h4><?php echo $this->translate('Translations') ?></h4>
                        </div>

                        <ul id="myTab" class="nav nav-tabs pattern">
                            <li class="dropdown">
                                <?php foreach($this->languages as $key => $language): ?>
                                <li class="<?php if($language == 'pl'): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                                <?php endforeach; ?>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <?php foreach($this->languages as $key => $language): ?>
                            <div class="tab-pane<?php if($language == 'pl'): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                                <span class="section contentSection">
                            <?php if($this->form->translations&&$this->form->translations->getSubForm($language)): ?>
                                <?php echo $this->form->translations->getSubForm($language)->name ?>
                                <?php echo $this->form->translations->getSubForm($language)->description->setAttrib('class','tinymce')?>
                            <?php elseif($this->form->name): ?>
				<?php echo $this->form->name ?>
				<?php echo $this->form->description ?>
			    <?php endif; ?>
                                </span>
                                <span class="section metatagSection">
                                    <div class="title" style ="margin-top: 30px;">

                                        <h4>
                                            <span class="icon16 icomoon-icon-pencil"></span>
                                            <span><?php echo $this->translate('Metatags') ?></span>
                                        </h4>

                                    </div>
                                    <div class="content clearfix">
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_title; ?>
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_description; ?>
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_keywords; ?>
                                    </div>
                                </span>
                            </div>
                            <?php endforeach; ?>
                        </div>
                    </span>
                    <span class="section optionsSection">
                         <?php 
                        $otherSectionsElems = array('submit','name');
                        foreach($this->form->getElements() as $element): 
                            if(in_array($element->getName(),$otherSectionsElems))
                                continue;
                            
                            // dla categoryTree produktu
                            if($element->getName()=='category_id'&&isset($this->categoryTree)):
                                echo "<span style='display:none'>".$element."</span>";
                            else:
                                echo $element;
                            endif;
                            endforeach; ?>
                    </span>
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-'.$this->actionName, $this->moduleName) ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
                
                
            
            </div>
            
        </div>
    </div>
</div>

