<script type="text/javascript">
$(document).ready(function() {
   
    $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
    });
        
    $('#explorer2').dialog({
            autoOpen: false,
            modal: true,
            dialogClass: 'dialog',
    });
    <?php if(isset($this->element['photo_root_id'])&&strlen($this->element['photo_root_id'])):  ?>
            
            
    $("#itemContainer").delegate(".actionBtn .add", "click", function(e) {
        e.preventDefault();
        
        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-main-photo', 'media') ?>/id/<?php echo $this->element['photo_root_id']; ?>/elem/<?php echo $this->actionName; ?>/elem_id/<?php echo $this->element['id']; ?>/actionName/<?php echo $this->actionName; ?>/moduleName/<?php echo $this->moduleName; ?>",
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_container").html(resp.body);
                            $("#itemContainer").trigger('update');
                        }
                    }
                });

                $('#explorer').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
                    //multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });
    
    $("#itemContainer").delegate(".actionBtn .delete", "click", function(e) {
        e.preventDefault();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "<?php echo $this->adminUrl('remove-main-photo', 'media') ?>/id/<?php echo $this->element['photo_root_id']; ?>",
            success: function(resp) {
                if(resp.status == "success") {
                    $("#main_photo_container").html(resp.body);
                    $("#itemContainer").trigger('update');
                }
            }
        });
    });
    
     $("#itemCon").delegate("#add-photo", "click", function(e) {
        e.preventDefault();
        
        var elf = $('#elfinder2').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-photo', 'media') ?>/id/<?php echo $this->element['photo_root_id']; ?>/elem/<?php echo $this->actionName; ?>/elem_id/<?php echo $this->element['id']; ?>/actionName/<?php echo $this->actionName; ?>/moduleName/<?php echo $this->moduleName; ?>",
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_con").html(resp.body);
                            $("#itemCon").trigger('update');
                        }
                    }
                });

                $('#explorer2').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer2').dialog('open');
    });
    
    $("#itemCon").delegate(".actionBtn .move", "click", function(e) {
            e.preventDefault();
            $.ajax({
                type: "post",
                dataType: "json",
                url: "<?php echo $this->adminUrl('move-photo', 'media') ?>/id/" +$(this).attr('rel')+"/move/"+$(this).attr('move')+"/elem_id/<?php echo $this->element['id']; ?>/actionName/<?php echo $this->actionName; ?>/moduleName/<?php echo $this->moduleName; ?>",
                success: function(resp) {
                    if(resp.status == "success") {
                        $("#main_photo_con").html(resp.body);
                        $("#itemCon").trigger('update');
                    }
                }
            });
     });
     
      $("#itemCon").delegate(".actionBtn .delete", "click", function(e) {
        e.preventDefault();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "<?php echo $this->adminUrl('remove-photo', 'media') ?>/id/"+$(this).attr('rel')+"/elem_id/<?php echo $this->element['id']; ?>/actionName/<?php echo $this->actionName; ?>/moduleName/<?php echo $this->moduleName; ?>",
            success: function(resp) {
                if(resp.status == "success") {
                    $("#main_photo_con").html(resp.body);
                    $("#itemCon").trigger('update');
                }
            }
        });
    });
    
    <?php endif; ?>

    <?php if($this->categoryTree): ?>
        
         $("#category_tree_selection").dynatree({
        checkbox: true,  
        autoCollapse: true,
        minExpandLevel: 2
     });
    
     $("#category_tree_selection").click(function(){
        
        var selectedNodes = $("#category_tree_selection").dynatree("getTree").getSelectedNodes(); 

        var selectedKeys = $.map(selectedNodes, function(node){ 
            return node.data.key; 
        }); 
        
        var ids = new Array();
        for(var x=0; x<selectedKeys.length; x++){
            var id = selectedKeys[x];
            ids[x] = id.replace(/^node/, "");
        }
        
        $("#category_id option").each(function(i, elem) {
            $(elem).attr("selected", false);
        });
       
    
        for(id in ids) {
            var option = $("#category_id option[value="+ids[id]+"]");
            if(option) {
                $(option).attr("selected", "selected");
            }
        }   
     });
     
    <?php else: ?>
         $("#category_id").select2();
    <?php endif; ?>



     $('.section').hide();
     $('.contentSection').show();
     $('.btnList li').click(function(){
        var rel = $(this).attr('rel');
        $('.section').hide();
        $('.'+rel).show();
     });
     
     if(!$('li[rel="optionsSection"]').find('input')){
	 $('li[rel="optionsSection"]').css('display','none');
     }
});
</script>
<?php
$elemArray = $this->element->toArray(); ?>
<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">
                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit '.$this->actionName) ?> <?php 
			    if(isset($this->element->Translation))
				echo $this->element->Translation[$this->language]->name;
			    else
				 echo $this->element->name;
			    ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                <ul class="btnList">
                    <li rel="contentSection"><button class="btn" type="button">Treść</button></li>
                    <li rel="optionsSection"><button class="btn" type="button">Opcje</button></li>
                    
                    <?php if(strlen($elemArray['photo_root_id'])): ?>
                    <li rel="photoSection"><button class="btn" type="button">Zdjęcia</button></li>
                     <?php endif; ?>
                    
                    <?php if(strlen($elemArray['video_root_id'])): ?>
                     <li rel="videoSection"><button class="btn" type="button">Video</button></li>
                     <?php endif; ?>
                    <li rel="metatagSection"><button class="btn" type="button">Pokaż metatagi</button></li>
                </ul>
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    
                    <span class="section contentSection metatagSection">
                        <div class="page-header">
                            <h4><?php echo $this->translate('Translations') ?></h4>
                        </div>

                        <ul id="myTab" class="nav nav-tabs pattern">
                            <li class="dropdown">
                                <?php foreach($this->languages as $key => $language): ?>
                                <li class="<?php if($language == 'pl'): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                                <?php endforeach; ?>
                            </li>   
                        </ul>

                        <div class="tab-content">
                            <?php foreach($this->languages as $key => $language): ?>
                            <div class="tab-pane<?php if($language == 'pl'): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">
                                <span class="section contentSection">
                            <?php if($this->form->translations&&$this->form->translations->getSubForm($language)): ?>
                                <?php echo $this->form->translations->getSubForm($language)->name ?>
                                <?php echo $this->form->translations->getSubForm($language)->description->setAttrib('class', 'tinymce') ?>
                             <?php elseif($this->form->name): ?>
				<?php echo $this->form->name ?>
				<?php echo $this->form->description ?>
			    <?php endif; ?>
                                </span>
                                <span class="section metatagSection">
                                    <div class="title" style ="margin-top: 30px;">

                                        <h4>
                                            <span class="icon16 icomoon-icon-pencil"></span>
                                            <span><?php echo $this->translate('Metatags') ?></span>
                                        </h4>

                                    </div>
                                    <div class="content clearfix">
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_title; ?>
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_description; ?>
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_keywords; ?>
                                    </div>
                                </span>
                            </div>
                            <?php endforeach; ?>
                        </div>
                        
                    </span>
                    <span class="section optionsSection">
                        <?php 
                        $otherSectionsElems = array('submit','name');
                        foreach($this->form->getElements() as $element): 
                            if(in_array($element->getName(),$otherSectionsElems))
                                continue;
                            
                            // dla categoryTree produktu
                            if($element->getName()=='category_id'&&isset($this->categoryTree)):
                                echo "<span style='display:none'>".$element."</span>";
                            else:
                                echo $element;
                            endif;
                            endforeach; ?>
                        
                        <?php if(isset($this->categoryTree)): ?>
                        <?php if ($this->form->category_id->hasErrors()): ?>
                          <div class="box" style="border: 1px solid red; width: 97%;">     
                        <?php else: ?>
                          <div class="box" style="border: 1px solid black; width: 97%;"> 
                        <?php endif; ?>
                            <div class="title">
                            <h4>
                                <span class="icon16 iconic-icon-list-nested"></span>
                                <span><?php echo $this->translate('Categories') ?></span>
                            </h4>

                            </div>
                            <div id="category_tree_selection">
                                <?php echo $this->partial('category-tree-selection.phtml', 'product', array('tree' => $this->categoryTree, 'parent' => $this->parent, 'selectedIds' => $this->form->category_id->getValue(), 'adminLanguage' => 'pl')) ?>
                            </div>    
                          </div>
                        <?php endif; ?>
                        
                    </span>
                    <?php if(strlen($elemArray['photo_root_id'])): ?>
                    <span class="section photoSection">
                        <div class="page-header">
                            <h4><?php echo $this->translate('Main photo') ?></h4>
                        </div>

                        <div id="itemContainer">
                            <ul id="main_photo_container" class="galleryView center">
                                <?php echo $this->partial('admin/main-photo.phtml', 'media', array('photos' => $this->element->get('PhotoRoot'), 'actionName' => $this->actionName, 'elem_id' => $this->element['id'], 'moduleName' => $this->moduleName)) ?>
                            </ul>
                        </div>

                         <div class="page-header">
                             <h4><?php echo $this->translate('Gallery View') ?></h4>
                        </div>                  
                        <div id="itemCon">           
                            <button href="#" id="add-photo" style="width: 120px;"><?php echo $this->translate('Add photo') ?></button>
                            <ul id="main_photo_con" class="galleryView center">                           
                                    <?php echo $this->partial('admin/photo-list.phtml', 'media', array('photos' => $this->element->get('PhotoRoot')->getNode()->getChildren(), 'actionName' => $this->actionName, 'elem_id' => $this->element['id'], 'moduleName' => $this->moduleName)) ?>
                            </ul>
                        </div>
                    </span>
                    <?php endif; ?>
                    <!-- videos -->
                    
                    <?php if($elemArray['video_root_id']): ?>
                    <span class="section videoSection">
                        <div class="box" style="width: 97%">
                            <div class="title">
                                <h4>
                                    <span class="icon16 entypo-icon-attachment"></span>
                                    <span><?php echo $this->translate('Videos') ?></span>
                                    <div class="box-form right">
                                        <button name="add_video" type="submit" class="btn btn-success btn-mini nostyle" id="add_video"><?php echo $this->translate('Add video') ?></button>
                                    </div>
                                </h4>  
                            </div>    
                            <div class="content clearfix">
                                <table id="video_table" cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" width="100%">
                                    <thead>
                                        <th><?php  echo $this->translate('Video') ?></th>
                                        <th><?php echo $this->translate('Options') ?></th>
                                    </thead>
                                    <?php if($this->element->get('VideoRoot')->getNode()->hasChildren()): ?>
                                    <tbody> 
                                       <?php foreach($this->element->get('VideoRoot')->getNode()->getChildren() as $video): ?>
                                            <tr>
                                                <th><iframe id="videoPreview" width="220" height="115" frameborder="0" allowfullscreen src="<?php echo $video->url; ?>"></iframe></th>
                                                <th style="width:50px;">
                                                    <a href="<?php  echo $this->adminUrl('remove-video', 'news', array('id' => $video->id,'news-id' => $this->element->id)); ?>" class="remove3" title="<?php echo $this->translate('Remove'); ?>"><span class="icon16 icon-remove"></span></a>
                                                </th>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                    <?php endif; ?>
                                </table>
                            </div>
                        </div>
                    </span>
                    <?php endif; ?>
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <button name="save_only" id="btnSaveOnly" type="submit" class="btn btn-primary"><?php echo $this->translate('Save and stay') ?></button>
                        <a href="<?php echo $this->adminUrl('list-news', 'news') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            </div>
            
        </div>
    </div>   
</div> 
<div id="explorer" class="dialog"><div id="elfinder"></div></div>
<div id="explorer2" class="dialog"><div id="elfinder2"></div></div>
    