<div class="seeGarage">
    <img src="http://unique.localhost/media/elfinder/klaudiusz-1024x564.jpg" alt="klaudiusz-1024x564" width="100%" height="500" />
    <a id="seeGarage" href="javascript:void(0)">Zobacz <br /> garaż</a>
</div>
<div class="outerWrapper">
    <div class="block_breadcrumbs">
                        	<div class="text"><p>Tu jesteś:</p></div>
                            
                            <ul>
                            	<li><a href="/">Strona główna</a></li>
                            	<li><a href="<?php echo $this->url(array(),'domain-gallery-list'); ?>">Galeria</a></li>
                                <li><?php echo $this->page['Translation'][$this->language]['name'] ?></li>
                            </ul>
                        </div>
    
    <div class="innerWrapper">
	<div class="pixel"></div>
    <h1><?php echo $this->gallery['Translation'][$this->language]['name'] ?></h1>
<?php echo $this->gallery['Translation'][$this->language]['description'] ?>

    <div class="gallery-container gallery-list">

                <div class="gallery-box">
                        <div class="row">
                
	<ul class="galleryList">
                    <?php foreach($this->gallery['Photos'] as $photo): ?>
                    <li>
                        <a class="rsImg" data-rsbigimg="/media/photos/<?php echo $photo['offset']; ?>/<?php echo $photo['filename']; ?>" href="/media/photos/<?php echo $photo['offset']; ?>/<?php echo $photo['filename']; ?>">
                            <img class="rsTmb" src="/media/photos/<?php echo $photo['offset']; ?>/266x150/<?php echo $photo['filename']; ?>">
                        </a>
                   </li>
                    <?php endforeach; ?>

                </ul>
            </div>


                </div>

            </div>

    </div>
</div>