<?php

/**
 * Newsletter_Model_Doctrine_BaseSubscriber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $lastname
 * @property string $email
 * @property boolean $send
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $MessageSubscribers
 * 
 * @package    Admi
 * @subpackage Newsletter
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Newsletter_Model_Doctrine_BaseSubscriber extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter_subscriber');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('send', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Newsletter_Model_Doctrine_Group as Groups', array(
             'refClass' => 'Newsletter_Model_Doctrine_SubscriberGroup',
             'local' => 'subscriber_id',
             'foreign' => 'group_id'));

        $this->hasMany('Newsletter_Model_Doctrine_MessageSubscriber as MessageSubscribers', array(
             'local' => 'id',
             'foreign' => 'subscriber_id'));
    }
}