<section id="Services" class="section section-white" style="display:none" >
  <div class="container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <header class="section-header ">
          <div class=" animated" data-animation="bounceInLeft"> <i class="autologo_avto"></i> </div>
          <div class="heading-wrap">
            <h2 class="heading" ><span> Featured Services</span></h2>
          </div>
          <p> We offer great vehicle services for our customers round the clock. </p>
        </header>
      </div>
    </div>
    <div class="row animated service-item"  data-animation="fadeInUp"> 
      
      <div class="col-lg-3 col-md-3 col-sm-3">
        <article class=" clearfix animated text-center"  data-animation="fadeInUp"> <i class="auto4"></i>
          <h4>ENGINE INSTALLMENT</h4>
          <p>Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum muslobortis consequat purus.</p>
        </article>
      </div>
      
    </div>
  </div>
</section>


<section id="Services2" style="background-image:url(/assets/media/services/bg.png); display:none;">
  <div class="container list-service" >
    <div class="row "> 
      
      <!-- BEGIN -->
      <div class="col-lg-3 col-md-3 col-sm-3">
        <article class=" clearfix  text-left" > 
          
          <!-- Nav tabs -->
          <ul class="nav nav-tabs ">
            <li><i class="auto5"></i><a href="#tab1-1" data-toggle="tab">AUDIO SYSTEMS</a></li>
            <li class="active" ><i class="auto6"></i><a href="#tab1-2" data-toggle="tab"> Creative</a></li>
            <li><i class="auto7"></i><a href="#tab1-3" data-toggle="tab">Technology</a></li>
          </ul>
        </article>
      </div>
      
      <!-- Tab panes -->
      <div class="tab-content ">
        <div class="tab-pane active " id="tab1-2">
          <div class="col-xs-12 col-sm-5 col-lg-6 ">
            <article class="clearfix text-left" > <i class="auto6"></i>
              <h3>Creative</h3>
              <p>Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum  Vivamus
                lobo rtis consequat purus. Curabitur commodo. Eltiam sed nulla. Lorem ipsum dolor sit
                met conse clt etuer adipiscing elit. Nulla libero. </p>
              <p>Donec convallis elementum leo. Duis ald ipiscing nulla elt metus. Donec gravida tortora massa. Fusce fermentum neque a rutrum varius odio. </p>
            </article>
          </div>
          <div class="col-xs-12 col-sm-4 col-lg-3">
            <article class="clearfix text-left" >
              <h4>Key Points</h4>
              <hr>
              <ul class="check-list">
                <li><i class="fa fa-check"></i>Integer mollis ullam corper metus proin </li>
                <li><i class="fa fa-check"></i> Maecenas commodo ed soll</li>
                <li><i class="fa fa-check"></i>Etiam ante lectus, venenatis at </li>
                <li><i class="fa fa-check"></i> Etiam ante lectus, venenatis at</li>
                <li><i class="fa fa-check"></i>Maecenas commodo ed soll</li>
              </ul>
            </article>
          </div>
        </div>
      </div>
      
    </div>
  </div>
</section>



<section id="portfolio" class="section" style="display:none" >
  <div class="container">
    <div class="row " >
      <div class="col-md-offset-3 col-md-6">
        <header class="section-header section-header-type2">
          <div class="heading-wrap">
            <h2 class="heading heading-type2" ><span>LATEST OFFERS</span></h2>
          </div>
          <p>Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus</p>
        </header>
      </div>
    </div>
  </div>
  <div class="row text-center animated" data-animation="bounceInRight">
    <div class="portfolio-filter-wrap">
      <ul class="portfolio-filter clearfix">
        <li><a href="javascript:void(0)"  onclick="return false;" class="btn btn-primary" data-filter="*">All</a></li>
        <li><a href="javascript:void(0)"  onclick="return false;" class="btn btn-default" data-filter=".filter-1">Cars</a></li>
        <li><a href="javascript:void(0)"  onclick="return false;"  class="btn btn-default" data-filter=".filter-2">Sport</a></li>
        <li><a  href="javascript:void(0)"  onclick="return false;" class="btn btn-default" data-filter=".filter-3">Trucks</a></li>
        <li><a  href="javascript:void(0)"  onclick="return false;" class="btn btn-default" data-filter=".filter-4">Bike</a></li>
      </ul>
    </div>
    <div class="portfolio-frame">
      <div class="portfolio-slider sly-frame">
        <div class="portfolio-item filter-1">
          <div class="item-thumbnail"> <a href="#"> <img alt="img"   src="/assets/media/portfolio/1.png" ></a>
            <p class="car-title">OPEL INSIGNIA</p>
          </div>
          <div class="item-hover">
            <div class="details">
              <div class="table">
                <div class="vertical-center">
                  <div class="detail-item">
                    <ul>
                      <li><i class="auto17"></i> <span>12,000</span></li>
                      <li> <i class="auto18"></i> <span> 2014,</span></li>
                      <li> <i class="auto19"></i> <span> 9,500</span></li>
                    </ul>
                  </div>
                  <a href="/assets/media/portfolio/5.png"  class="btn">more</a> </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="portfolio-navigation"> <a class="btn btn-primary slider-direction prev-page" href="javascript:void(0);"><i class="icomoon-arrow-left2"></i></a> <a class="btn btn-primary slider-direction next-page" href="javascript:void(0);"><i class="icomoon-arrow-right2"></i></a>
      <ul class="pages unstyled">
      </ul>
    </div>
  </div>
</section>

<?php echo $this->oUniqueGarage['Translation'][$this->language]['description']; ?>


<?php echo $this->celeNaszejFirmy['Translation'][$this->language]['description']; ?>


<?php echo $this->naszZespol['Translation'][$this->language]['description']; ?>


<section id="facts" class="section section-bg"  style="background-image:url(/assets/media/numbers/bg.png); display:none" >
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-9">
        <header class="section-header-simple">
          <div class="heading-wrap">
            <h2 class="heading"> <span>ZAJMUJEMY SIĘ RÓŻNYMI ELEMENTAMI SAMOCHODU</span></h2>
          </div>
        </header>
      </div>
    </div>
    <div class="row text-center animated" data-animation="bounceIn"> 
      <script src="/assets/js/jquery.easing.1.3.js"></script> 
      <script src="/assets/js/jquery.easypiechart.js"></script> 
      
      <!-- BEGIN -->
      <div class="col-xs-12 col-sm-12 col-lg-12">
        <article data-animation="fadeInDown" class="numbers clearfix animated text-left  fadeInDown">
          <ul>
            <li>
              <div class="overflow-offer"> <a href="#" class="wrap-offer"> <i class="auto12"></i>
                <p class="offer-name">TAPICERKA</p>
                </a> </div>
              <span class="span-title"><span class="chart" data-percent="99"> <span class="percent"></span> </span> WIĘCEJ</span> </li>
            <li>
              <div class="overflow-offer"> <a href="#" class="wrap-offer"> <i class="auto13"></i>
                <p class="offer-name">PLASTIKI</p>
                </a></div>
              <span class="span-title"><span class="chart" data-percent="96"> <span class="percent"></span> </span> WIĘCEJ</span></li>
            <li>
              <div class="overflow-offer"><a href="#" class="wrap-offer"> <i class="auto14"></i>
                <p class="offer-name">LAKIER</p>
                </a> </div>
              <span class="span-title"><span class="chart" data-percent="89"> <span class="percent"></span> </span> WIĘCEJ</span></li>
            <li>
              <div class="overflow-offer"><a href="#" class="wrap-offer"> <i class="auto15"></i>
                <p class="offer-name">FELGI</p>
                </a> </div>
              <span class="span-title"><span class="chart" data-percent="86"> <span class="percent"></span> </span> WIĘCEJ</span></li>
            <li>
              <div class="overflow-offer"> <a href="#" class="wrap-offer"> <i class="auto16"></i>
                <p class="offer-name">SZYBY</p>
                </a></div>
              <span class="span-title"><span class="chart" data-percent="54"> <span class="percent"></span> </span> WIĘCEJ</span></li>
          </ul>
        </article>
      </div>
    </div>
  </div>
</section>

<!-- REVIEWS SECTION-->
<section class="section section-white" id="our-reviews" style="display:none">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
      
         <header class="section-header">
          <div class=" animated" data-animation="bounceInLeft"> <i class="autologo_avto"></i> </div>
          <div class="heading-wrap">
            <h2 class="heading " ><span>OUR Reviews</span></h2>
          </div>
        </header>
        
        
        
      </div>
    </div>
  </div>
  <div class="container">
    <div  class="row text-center">
      <div class="reviews-frame " >
        <ul class="review-slider" >
          <li>
            <div data-animation="fadeIn" class="team-member animated  fadeIn">
              <div class="avatar-review"> <img src="/assets/media/team/1.png" alt="img"></div>
              <div class="details-review">
                <div class="desc-det"> Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum muslobortis consequat purus. Duis viverra malesuada mi. Fusce ante augue, convallis sit am
                  et volutpat ac, posuere vel, quam. </div>
                <div class="review-autor">
                  <h3 class="heading">John Deo</h3>
                  <h4 class="sub-heading">CAR OWNER</h4>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="portfolio-navigation"> <a class="btn btn-primary slider-direction prev-page disabled" href="javascript:void(0);"><i class="icomoon-arrow-left2"></i></a> <a class="btn btn-primary slider-direction next-page" href="javascript:void(0);"><i class="icomoon-arrow-right2"></i></a>
        <ul class="pages unstyled">
          <li class="active">1</li>
        </ul>
      </div>
    </div>
  </div>
</section>



<!-- BRAND -->
<section id="our-clients" class="section" style="background:#f4f4f4;display:none" >
  <div class="container">
    <div class="row ">
      <div class="col-md-offset-3 col-md-6">
        <header class="section-header section-header-type2">
          <div class="heading-wrap">
            <h2 class="heading heading-type2"><span>POPULAR BRANDS</span></h2>
          </div>
        </header>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row  " >
      <table >
        <tr class="first">
          <td class="first"><a href="#" ><img alt="img"   src="/assets/media/brands/1.png" ></a></td>
          <td><a href="#"><img alt="img"   src="/assets/media/brands/2.png" ></a></td>
          <td><a href="#"><img alt="img"   src="/assets/media/brands/3.png" ></a></td>
          <td><a href="#"><img alt="img"   src="/assets/media/brands/4.png" ></a></td>
 
        </tr>
      </table>
    </div>
  </div>
</section>
