<iframe class="w_full" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2565.5720570743197!2d20.069302099999998!3d49.981883499999995!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47164165aab72e31%3A0x2b75df7809f08e72!2sS%C5%82owackiego+64%2C+32-020+Wieliczka!5e0!3m2!1spl!2spl!4v1415302538616"  height="400" ></iframe>
<section class="section_offset contact">
	<div class="container clearfix">
		<div class="row">
			<div class="col-lg-7 col-md-7 col-sm-7 m_xs_bottom_30">
				<h3 class="color_dark fw_light m_bottom_15 heading_1 t_align_c">Kontakt</h3>
				<div class="row">
					<ul class="col-lg-6 col-md-6 col-sm-6 fw_light w_break m_bottom_45 m_xs_bottom_30">
						<li class="m_bottom_8">
							<div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
								<i class="icon-phone-1"></i>
							</div>
							692-407-535
						</li>
						<li class="m_bottom_8">
							<div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
								<i class="icon-mail-alt"></i>
							</div>
							<a href="mailto:floraart.bb@gmail.com" class="color_black color_pink_hover">floraart.bb(at)gmail.com </a>
						</li>
						<li class="m_bottom_8 fw_light">
							<div class="f_left icon_wrap_size_1 color_pink circle m_right_10">
								<i class="icon-location"></i>
							</div>
							Słowackiego 64, Kraków<br /> (pasaż handlowy Herbewo)
						</li>
					</ul>
					<ul class="col-lg-6 col-md-6 col-sm-6 m_xs_bottom_30 vr_list_type_5">
					    <li class="fw_light m_bottom_8">
						    <div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
							    <i class="icon-lifebuoy"></i>
						    </div>
						    <a href="http://www.pakamera.pl/floraart-0_s12086052.htm" class="color_dark color_pink_hover">Sklep Flora Art</a>
					    </li>
					    <li class="fw_light m_bottom_8">
						    <div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
							    <i class="icon-lifebuoy"></i>
						    </div>
						    <a href="http://floraservice.blogspot.com/" class="color_dark color_pink_hover">Blog Flora Art</a>
					    </li>
					    <li class="m_bottom_8">
						    <div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
							    <i class="icon-facebook fs_small"></i>
						    </div>
						    <a href="https://www.facebook.com/pages/FloraArt/255657294534741?ref=hl" class="color_black color_pink_hover">FloraArt</a>
					    </li>
				    </ul>
				</div>
				
				<?php echo $this->page['Translation'][$this->language]['description']; ?>
			</div>
			
		      <div class="col-xs-5 col-sm-5 col-lg-5">
			  <?php echo $this->messages()->render(); ?>
			<h3 class="color_dark fw_light m_bottom_15 heading_1 t_align_c">Napisz do nas</h3>
			<form id="" class="form-full-width contact-form" method="POST">
			  <div class="row">
			    <div class="col-xs-12 col-sm-12 m_bottom_15">
			      <div class="form-group">
				<input placeholder="Imie" value="<?php echo $_POST['name'];?>" type="text" id="contact-subject1" name="name" />
			      </div>
			    </div>
			   <div class="col-xs-6 col-sm-6 m_bottom_15">
			      <div class="form-group">
				<input placeholder="Email*" type="text" value="<?php echo $_POST['email'];?>" id="contact-subject2" name="email" />
			      </div>
			    </div>
			    <div class="col-xs-6 col-sm-6 m_bottom_15">
			      <div class="form-group">
				<input placeholder="Telefon" type="text" value="<?php echo $_POST['phone'];?>" id="contact-subject2" name="phone" />
			      </div>
			    </div>
			    <div class="col-xs-12 col-sm-12 m_bottom_15">
			      <div class="form-group">
				<textarea placeholder="Wiadomość" id="contact-message" name="message" > <?php echo $_POST['message'];?></textarea>
			      </div>
			    </div>
			      <?php echo $this->form->captcha; ?>
			    <div class="col-xs-12 col-sm-12 text-left">
			      <div class="wrap-main">
				  <button id="contact-submit" class="button_type_5 color_blue transparent r_corners fs_medium tr_all m_right_10 m_sm_bottom_10">Wyślij</button>
				
			      </div>
			    </div>
			  </div>
			</form>

		      </div>
		</div>
	</div>
</section>