
<footer role="contentinfo" class="bg_light_3">
				<!--top part-->
				<section class="footer_top_part">
					<div class="container">
						<div class="row">
							<!--about us-->
							<div class="col-lg-4 col-md-4 col-sm-4 fw_light m_bottom_30">
								<h5 class="color_dark m_bottom_20">Prawa autorskie</h5>
								<p>Wszystkie prezentowane na tej stronie przedmioty, zdjęcia oraz teksty są mojego autorstwa (jeśli jest inaczej – wówczas wyraźnie to zaznaczam). Nie zezwalam na ich kopiowanie i rozpowszechnianie bez mojej wiedzy i zgody. Uszanuj proszę moją pracę.</p>
							</div>
							<!--contact info--> 
							<div class="col-lg-5 col-md-5 col-sm-5 m_bottom_30">
								<h5 class="color_dark m_bottom_20 fw_light">Skontaktuj się z nami</h5>
								<div class="row">
									<ul class="col-lg-6 col-md-6 col-sm-6 fw_light w_break m_bottom_45 m_xs_bottom_30">
										<li class="m_bottom_8">
											<div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
												<i class="icon-phone-1"></i>
											</div>
											692-407-535
										</li>
										<li class="m_bottom_8">
											<div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
												<i class="icon-mail-alt"></i>
											</div>
											<a href="mailto:floraart.bb@gmail.com" class="color_black color_pink_hover">floraart.bb(at)gmail.com </a>
										</li>
										<li class="m_bottom_8 fw_light">
											<div class="f_left icon_wrap_size_1 color_pink circle m_right_10">
												<i class="icon-location"></i>
											</div>
											Słowackiego 64, Kraków<br /> (pasaż handlowy Herbewo)
										</li>
									</ul>
									<ul class="col-lg-6 col-md-6 col-sm-6 m_xs_bottom_30 vr_list_type_5">
									    <li class="fw_light m_bottom_8">
										    <div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
											    <i class="icon-lifebuoy"></i>
										    </div>
										    <a href="http://www.pakamera.pl/floraart-0_s12086052.htm" class="color_dark color_pink_hover">Sklep Flora Art</a>
									    </li>
									    <li class="fw_light m_bottom_8">
										    <div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
											    <i class="icon-lifebuoy"></i>
										    </div>
										    <a href="http://floraservice.blogspot.com/" class="color_dark color_pink_hover">Blog Flora Art</a>
									    </li>
									    <li class="m_bottom_8">
										    <div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
											    <i class="icon-facebook fs_small"></i>
										    </div>
										    <a href="https://www.facebook.com/pages/FloraArt/255657294534741?ref=hl" class="color_black color_pink_hover">FloraArt</a>
									    </li>
								    </ul>
								</div>
							</div>
							<!--social buttons-->
							<div class="col-lg-3 col-md-3 col-sm-3 m_bottom_30 m_xs_bottom_20">
								<h5 class="color_dark fw_light m_bottom_15">Dołącz do nas na Facebooku</h5>
								<div class="fb-like-box" data-href="https://www.facebook.com/pages/FloraArt/255657294534741?ref=hl" data-width="250" data-height="200" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
							</div>
						</div>
					</div>
				</section>
				<!--bottom part-->
				<section class="footer_bottom_part t_align_c color_grey bg_light_4 fw_light">
				    <p>© 2014 Flora Art. All Rights Reserved. Wykonanie : <a href="http://kardimobile.pl">Kardi mobile</a></p>
				</section>
			</footer>

	 <button id="back_to_top" class="circle icon_wrap_size_2 color_blue_hover color_grey_light_4 tr_all d_md_none">
            <i class="icon-angle-up fs_large"></i>
        </button>

	    <div id="fb-root"></div>
	    <script>(function(d, s, id) {
	      var js, fjs = d.getElementsByTagName(s)[0];
	      if (d.getElementById(id)) return;
	      js = d.createElement(s); js.id = id;
	      js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&appId=1414118592157826&version=v2.0";
	      fjs.parentNode.insertBefore(js, fjs);
	    }(document, 'script', 'facebook-jssdk'));</script>
        <script src="/assets/js/isotope.pkgd.min.js"></script>
        <script src="/plugins/jquery.elevateZoom-3.0.8.min.js"></script>
        <script src="/plugins/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
        <script src="/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
        <script src="/assets/js/jquery.appear.js"></script>
        <script src="/assets/js/afterresize.min.js"></script>
        <script src="/assets/js/jquery.easing.1.3.js"></script>
        <script src="/assets/js/jquery.easytabs.min.js"></script>
        <script src="/assets/plugins/jackbox/js/jackbox-packed.min.js"></script>
	
        <script src="//cdn.jsdelivr.net/jquery.marquee/1.3.1/jquery.marquee.min.js" type="text/javascript"></script>
        <script src="/plugins/owl-carousel/owl.carousel.min.js"></script>
        <script src="/assets/js/flickr.js"></script>

        <!--Theme Initializer-->
        <script src="/assets/js/theme.plugins.js"></script>
        <script src="/assets/js/theme.js"></script>