<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="index,follow" />
<meta name="author" content="kardimobile.pl" />

<?php echo $this->headMeta(); ?>
<title><?php echo strip_tags($this->headTitle()); ?> - Flora Art</title>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<!-- Favorite Icons -->
<link rel="shortcut icon" href="/images/layout/favicon.ico" type="image/x-icon">
<link rel="icon" href="/images/layout/favicon.ico" type="image/x-icon">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/img/favicon/favicon-144x144.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/img/favicon/favicon-72x72.png">
<link rel="apple-touch-icon-precomposed" href="/assets/img/favicon/favicon-54x54.png">
<!-- // Favorite Icons -->


<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,700,800&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<!--libs css-->
<link rel="stylesheet" type="text/css" media="all" href="/plugins/owl-carousel/owl.carousel.css">
<link rel="stylesheet" type="text/css" media="all" href="/plugins/owl-carousel/owl.transitions.css">
<link rel="stylesheet" type="text/css" media="screen" href="/plugins/rs-plugin/css/settings.css">
<link rel="stylesheet" type="text/css" media="print" href="/css/print.css">
<meta name="google-site-verification" content="XTob1hj1hT1M3yly67o6A1RclrutOoJcXhkr1S7km3Q" />
<meta name="msvalidate.01" content="91139913A914C67B51C76DFACF22B0E7" />
<meta name="p:domain_verify" content="0492131b615d97ce14fb5e0a3a3bc473"/>
<!--theme css-->
<link rel="stylesheet" type="text/css" media="all" href="/assets/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" media="all" href="/assets/css/theme-animate.css">
<link rel="stylesheet" type="text/css" media="all" href="/assets/css/style.css">

<link rel="stylesheet" type="text/css" media="all" href="/assets/plugins/jackbox/css/jackbox.min.css">
<link rel="stylesheet" type="text/css" media="all" href="/css/custom.css">
<!--head libs-->
<script src="/js/jquery-2.1.0.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" media="all" href="/css/cookiecuttr.css">
<script src="/js/jquery.cookie.js"></script>
<script src="/js/jquery.cookiecuttr.js"></script>
<script src="/assets/js/jquery.queryloader2.min.js"></script>
<script src="/assets/js/modernizr.js"></script>

