<div class="loginContainer">
    <h2 claas="title"><?php echo $this->translate('Enter your email') ?></h2>
     <?php echo $this->messages()->render() ?>
    <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" id="loginForm" method="post" >
        <div class="form-row row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <?php echo $this->form->email ?>
                </div>
            </div>
        </div>
        <div class="form-row row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <?php echo $this->form->captcha ?>
                </div>
            </div>
        </div>

        <div class="form-row row-fluid">                       
            <div class="span12">
                <div class="row-fluid">
                    <div class="form-actions">
                    <div class="span12 controls">
                        <button type="submit" class="btn btn-info right" id="loginBtn"><span class="icon16 icomoon-icon-enter white"></span> <?php echo $this->translate('Send new password') ?></button>
                    </div>
                    </div>
                </div>
            </div> 
        </div>
    </form>
</div>