<div class="loginContainer recoverPasswordComplete">
    <?php echo $this->messages()->render() ?>
    <h2 claas="title"><?php echo $this->translate('Set new password') ?></h2>
    <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" id="loginForm" method="post" >
        <div class="form-row row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <?php echo $this->form->password ?>
                </div>
            </div>
        </div>

        <div class="form-row row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <?php echo $this->form->confirm_password ?>
                </div>
            </div>
        </div>
        <div class="form-row row-fluid">                       
            <div class="span12">
                <div class="row-fluid">
                    <div class="form-actions">
                    <div class="span12 controls">
                        <button type="submit" class="btn btn-info right" id="loginBtn"><span class="icon16 icomoon-icon-enter white"></span> <?php echo $this->translate('Save') ?></button>
                    </div>
                    </div>
                </div>
            </div> 
        </div>
        <?php echo $this->form->csrf ?>
    </form>
</div>
   