Witaj,<br />
ten mail został wysłany z portalu twojasilownia.com.pl w celu przypomnienia hasła użytkownika. Aby zmienić swoje hasło kliknij w poniższy link<br />
<a href="<?php echo $this->url(array('token' => $this->token), 'domain-recover-password-complete') ?>"><?php echo $this->url(array('token' => $this->token), 'domain-recover-password-complete') ?></a> <br />
<br />
Uwaga! Jeżeli nie prosiłeś o zmianę hasła do Twojego konta na portalu twojasilownia.com.pl zignoruj tego maila<br />
Pozdrawiamy, zespół twojasilownia.com.pl 
