

<!DOCTYPE HTML>
<!--[if IE 7 ]><html class="ie ie7 lte9 lte8 lte7" lang="en-US"><![endif]-->
<!--[if IE 8]><html class="ie ie8 lte9 lte8" lang="en-US">	<![endif]-->
<!--[if IE 9]><html class="ie ie9 lte9" lang="en-US"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="pl" class="noIE">
<head>
  <?php echo $this->render('_head.phtml'); ?>
</head>
<body class="onepage sticky-header">

    <?php echo $this->render('_header.phtml'); ?>
<!-- //PAGE HEADER --> 

<!-- HOME SLIDER -->
<section id="home" class="section  home-slider" >
   <?php echo $this->layout()->slider; ?>



  <!-- FlexSlider -->
  <script defer src="/assets/js/jquery.flexslider.js"></script>

  
  
  
  
</section>
<!-- // HOME SLIDER --> 

<!-- SERVICES SECTION -->
<section id="Services" class="section section-white" style="display:none">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <header class="section-header ">
          <div class=" animated" data-animation="bounceInLeft"> <i class="autologo_avto"></i> </div>
          <div class="heading-wrap">
            <h2 class="heading" ><span> Featured Services</span></h2>
          </div>
          <p> We offer great vehicle services for our customers round the clock. </p>
        </header>
      </div>
    </div>
    <div class="row animated service-item"  data-animation="fadeInUp"> 
      
      <!-- BEGIN -->
      <div class="col-lg-3 col-md-3 col-sm-3">
        <article class=" clearfix animated text-center"  data-animation="fadeInUp"> <i class="auto1"></i>
          <h4>ENGINE INSTALLMENT</h4>
          <p>Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum muslobortis consequat purus.</p>
        </article>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3">
        <article class=" clearfix animated text-center"  data-animation="fadeInUp"> <i class="auto2"></i>
          <h4>ENGINE INSTALLMENT</h4>
          <p>Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum muslobortis consequat purus.</p>
        </article>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3">
        <article class=" clearfix animated text-center"  data-animation="fadeInUp"> <i class="auto3"></i>
          <h4>ENGINE INSTALLMENT</h4>
          <p>Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum muslobortis consequat purus.</p>
        </article>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3">
        <article class=" clearfix animated text-center"  data-animation="fadeInUp"> <i class="auto4"></i>
          <h4>ENGINE INSTALLMENT</h4>
          <p>Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum muslobortis consequat purus.</p>
        </article>
      </div>
      
      <!-- Tab panes --> 
      
      <!-- END --> 
    </div>
  </div>
</section>

<section id="Services2" style="background-image:url(/assets/media/services/bg.png); display:none;">
  <div class="container list-service" >
    <div class="row "> 
      
      <!-- BEGIN -->
      <div class="col-lg-3 col-md-3 col-sm-3">
        <article class=" clearfix  text-left" > 
          
          <!-- Nav tabs -->
          <ul class="nav nav-tabs ">
            <li><i class="auto5"></i><a href="#tab1-1" data-toggle="tab">AUDIO SYSTEMS</a></li>
            <li class="active" ><i class="auto6"></i><a href="#tab1-2" data-toggle="tab"> Creative</a></li>
            <li><i class="auto7"></i><a href="#tab1-3" data-toggle="tab">Technology</a></li>
          </ul>
        </article>
      </div>
      
      <!-- Tab panes -->
      <div class="tab-content ">
        <div class="tab-pane " id="tab1-1">
          <div class="col-xs-12 col-sm-5 col-lg-6 ">
            <article class="clearfix  text-left" > <i class="auto5"></i>
              <h3>AUDIO SYATEMS</h3>
              <p>Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum  Vivamus
                lobo rtis consequat purus. Curabitur commodo. Eltiam sed nulla. Lorem ipsum dolor sit
                met conse clt etuer adipiscing elit. Nulla libero. </p>
              <p>Donec convallis elementum leo. Duis ald ipiscing nulla elt metus. Donec gravida tortora massa. Fusce fermentum neque a rutrum varius odio. </p>
            </article>
          </div>
          <div class="col-xs-12 col-sm-4 col-lg-3">
            <article class="clearfix  text-left" >
              <h4>Key Points</h4>
              <hr>
              <ul class="check-list">
                <li><i class="fa fa-check"></i>Etiam ante lectus, venenatis at </li>
                <li><i class="fa fa-check"></i>Maecenas commodo ed soll</li>
                <li><i class="fa fa-check"></i>Integer mollis ullam corper metus proin </li>
                <li><i class="fa fa-check"></i> Etiam ante lectus, venenatis at</li>
                <li><i class="fa fa-check"></i> Maecenas commodo ed soll</li>
              </ul>
            </article>
          </div>
        </div>
        <div class="tab-pane active " id="tab1-2">
          <div class="col-xs-12 col-sm-5 col-lg-6 ">
            <article class="clearfix text-left" > <i class="auto6"></i>
              <h3>Creative</h3>
              <p>Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum  Vivamus
                lobo rtis consequat purus. Curabitur commodo. Eltiam sed nulla. Lorem ipsum dolor sit
                met conse clt etuer adipiscing elit. Nulla libero. </p>
              <p>Donec convallis elementum leo. Duis ald ipiscing nulla elt metus. Donec gravida tortora massa. Fusce fermentum neque a rutrum varius odio. </p>
            </article>
          </div>
          <div class="col-xs-12 col-sm-4 col-lg-3">
            <article class="clearfix text-left" >
              <h4>Key Points</h4>
              <hr>
              <ul class="check-list">
                <li><i class="fa fa-check"></i>Integer mollis ullam corper metus proin </li>
                <li><i class="fa fa-check"></i> Maecenas commodo ed soll</li>
                <li><i class="fa fa-check"></i>Etiam ante lectus, venenatis at </li>
                <li><i class="fa fa-check"></i> Etiam ante lectus, venenatis at</li>
                <li><i class="fa fa-check"></i>Maecenas commodo ed soll</li>
              </ul>
            </article>
          </div>
        </div>
        <div class="tab-pane " id="tab1-3">
          <div class="col-xs-12 col-sm-5 col-lg-6 ">
            <article class="clearfix  text-left" > <i class="auto7"></i>
              <h3>Technology</h3>
              <p>Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum  Vivamus
                lobo rtis consequat purus. Curabitur commodo. Eltiam sed nulla. Lorem ipsum dolor sit
                met conse clt etuer adipiscing elit. Nulla libero. </p>
              <p>Donec convallis elementum leo. Duis ald ipiscing nulla elt metus. Donec gravida tortora massa. Fusce fermentum neque a rutrum varius odio. </p>
            </article>
          </div>
          <div class="col-xs-12 col-sm-4 col-lg-3">
            <article class="clearfix text-left" >
              <h4>Key Points</h4>
              <hr>
              <ul class="check-list">
                <li><i class="fa fa-check"></i>Etiam ante lectus, venenatis at </li>
                <li><i class="fa fa-check"></i>Integer mollis ullam corper metus proin </li>
                <li><i class="fa fa-check"></i> Maecenas commodo ed soll</li>
                <li><i class="fa fa-check"></i>Maecenas commodo ed soll</li>
                <li><i class="fa fa-check"></i> Etiam ante lectus, venenatis at</li>
              </ul>
            </article>
          </div>
        </div>
      </div>
      
      <!-- END --> 
    </div>
  </div>
</section>

<!-- // SERVICES SECTION -->


<?php echo $this->layout()->content; ?>


<!-- ABOUT -->
<section class="section section-white" id="about" style="display:none">
  <div class="container container-about" >
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <header class="section-header">
          <div class=" animated" data-animation="bounceInLeft"> <i class="autologo_avto"></i> </div>
          <div class="heading-wrap">
            <h2 class="heading"><span>ABOUT AUTOIMAGE</span></h2>
          </div>
        </header>
      </div>
    </div>
    <div class="row animated" data-animation="bounceInRight"> 
      
      <!-- BEGIN -->
      <div class="col-xs-12 col-sm-6 col-lg-6">
        <article class=" clearfix animated text-left" data-animation="fadeInDown"> 
          
          <!-- Nav tabs -->
          <ul class="nav nav-tabs ">
            <li><a href="#tab1" data-toggle="tab"><i class="auto8"></i><strong>WE ARE A TRUSTED NAME</strong>Cum sociis natoque penatibus et magnis dis parturient mo ntes, nascetur ridiculus mus. Quisque vel ante quis</a></li>
            <li class="active" ><a href="#tab2" data-toggle="tab"><i class="auto9"></i><strong>WE ARE AT WORLDWIDE LOCATIONS</strong>Cum sociis natoque penatibus et magnis dis parturient mo ntes, nascetur ridiculus mus. Quisque vel ante quis</a></li>
            <li><a href="#tab3" data-toggle="tab"> <i class="auto10"></i> <strong>WE HAVE A LARGER STOCK OF VEHICLES</strong>Cum sociis natoque penatibus et magnis dis parturient mo ntes, nascetur ridiculus mus. Quisque vel ante quis</a></li>
            <li><a href="#tab4" data-toggle="tab"><i class="auto11"></i><strong>WE DEAL IN HAVE ALL BRANDS</strong>Cum sociis natoque penatibus et magnis dis parturient mo ntes, nascetur ridiculus mus. Quisque vel ante quis</a></li>
          </ul>
        </article>
      </div>
      
      <!-- Tab panes -->
      <div class="tab-content col-xs-12 col-sm-6 col-lg-6">
        <div class="tab-pane " id="tab1">
          <article class="clearfix animated text-left" > <img src="/assets/media/about/2.jpg" class="img-responsive" alt="about" > </article>
        </div>
        <div class="tab-pane active " id="tab2">
          <article class="clearfix animated text-left" > <img src="/assets/media/about/1.jpg" class="img-responsive" alt="about" > </article>
        </div>
        <div class="tab-pane " id="tab3">
          <article class="clearfix animated text-left" > <img src="/assets/media/about/3.jpg" class="img-responsive" alt="about" > </article>
        </div>
        <div class="tab-pane " id="tab4">
          <article class="clearfix animated text-left" > <img src="/assets/media/about/4.jpg" width="885" height="487" class="img-responsive" alt="about"> </article>
        </div>
      </div>
      
      <!-- END --> 
    </div>
  </div>
</section>




<!-- COMPANY MISSION -->
<section class="section" id="mission" style="background:#f4f4f4;display:none;" >
  <div class="container">
    <div class="row ">
      <div class="col-md-offset-3 col-md-6">
        <header class="section-header section-header-type2">
          <div class="heading-wrap">
            <h2 class="heading heading-type2"><span>COMPANY MISSION</span></h2>
          </div>
         
        </header>
      </div>
      
      
      <div class="col-md-offset-2 col-md-8">
        <header class="section-header ">
          
          <p>Nam quis arcu sit amet est dictum volutpat. Vivamus quis sapien. Sed porttitor accumsan arcu.
            In risus auspendisse aliquam lacus vitae mauris Donec dolor nisl ultrices ac.</p>
        </header>
      </div>
      
      
    </div>
  </div>
</section>



<!-- OUR TEAM SECTION -->
<section id="our-team" class="section section-white" style="display:none">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <header class="section-header">
          <div class=" animated" data-animation="bounceInLeft"> <i class="autologo_avto"></i> </div>
          <div class="heading-wrap">
            <h2 class="heading " ><span>OUR TEAM</span></h2>
          </div>
        </header>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row text-center animated" data-animation="bounceInRight">
      <div class="team-frame">
        <ul class="team-slider">
          <li>
            <div class="team-member animated" data-animation="fadeIn">
              <div class="avatar-team"> <img alt="img"   src="/assets/media/team/1.png"></div>
              <div class="details-team">
                <h3 class="heading">John Deo</h3>
                <h4 class="sub-heading">OWNER</h4>
                <div class="desc-det"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's .
                  <section class="progress-section">
                    <div class="level-skill">Skill Level:</div>
                    <div class="progress-bar">
                      <div class="progress"></div>
                    </div>
                  </section>
                </div>
                <ul class="unstyled clearfix social-team">
                  <li><a  target="_blank" href="http://fb.com/#"><i class="icomoon-facebook"></i></a></li>
                  <li><a target="_blank" href="http://twitter.com/#"><i class="icomoon-twitter"></i></a></li>
                  <li><a target="_blank"  href="http://plus.google.com/#"><i class="icomoon-googleplus"></i></a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <div class="team-member animated" data-animation="fadeIn">
              <div class="avatar-team"> <img alt="img"   src="/assets/media/team/2.png"></div>
              <div class="details-team">
                <h3 class="heading">Mark Deo</h3>
                <h4 class="sub-heading">CO-OWNER</h4>
                <div class="desc-det"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's .
                  <section class="progress-section">
                    <div class="level-skill">Skill Level:</div>
                    <div class="progress-bar">
                      <div class="progress"></div>
                    </div>
                  </section>
                </div>
                <ul class="unstyled clearfix social-team">
                  <li><a  target="_blank" href="http://fb.com/#"><i class="icomoon-facebook"></i></a></li>
                  <li><a target="_blank" href="http://twitter.com/#"><i class="icomoon-twitter"></i></a></li>
                  <li><a target="_blank"  href="http://plus.google.com/#"><i class="icomoon-googleplus"></i></a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <div class="team-member animated" data-animation="fadeIn">
              <div class="avatar-team"> <img alt="img"   src="/assets/media/team/3.png"></div>
              <div class="details-team">
                <h3 class="heading">Jessica Smith</h3>
                <h4 class="sub-heading">BROKER</h4>
                <div class="desc-det"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's .
                  <section class="progress-section">
                    <div class="level-skill">Skill Level:</div>
                    <div class="progress-bar">
                      <div class="progress"></div>
                    </div>
                  </section>
                </div>
                <ul class="unstyled clearfix social-team">
                  <li><a  target="_blank" href="http://fb.com/#"><i class="icomoon-facebook"></i></a></li>
                  <li><a target="_blank" href="http://twitter.com/#"><i class="icomoon-twitter"></i></a></li>
                  <li><a target="_blank"  href="http://plus.google.com/#"><i class="icomoon-googleplus"></i></a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <div class="team-member animated" data-animation="fadeIn">
              <div class="avatar-team"> <img alt="img"   src="/assets/media/team/4.png"></div>
              <div class="details-team">
                <h3 class="heading">Stepan Deo</h3>
                <h4 class="sub-heading">MARKETER</h4>
                <div class="desc-det"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's .
                  <section class="progress-section">
                    <div class="level-skill">Skill Level:</div>
                    <div class="progress-bar">
                      <div class="progress"></div>
                    </div>
                  </section>
                </div>
                <ul class="unstyled clearfix social-team">
                  <li><a  target="_blank" href="http://fb.com/#"><i class="icomoon-facebook"></i></a></li>
                  <li><a target="_blank" href="http://twitter.com/#"><i class="icomoon-twitter"></i></a></li>
                  <li><a target="_blank"  href="http://plus.google.com/#"><i class="icomoon-googleplus"></i></a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <div class="team-member animated" data-animation="fadeIn">
              <div class="avatar-team"> <img alt="img"   src="/assets/media/team/1.png"></div>
              <div class="details-team">
                <h3 class="heading">John Deo</h3>
                <h4 class="sub-heading">OWNER</h4>
                <div class="desc-det"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's .
                  <section class="progress-section">
                    <div class="level-skill">Skill Level:</div>
                    <div class="progress-bar">
                      <div class="progress"></div>
                    </div>
                  </section>
                </div>
                <ul class="unstyled clearfix social-team">
                  <li><a  target="_blank" href="http://fb.com/#"><i class="icomoon-facebook"></i></a></li>
                  <li><a target="_blank" href="http://twitter.com/#"><i class="icomoon-twitter"></i></a></li>
                  <li><a target="_blank"  href="http://plus.google.com/#"><i class="icomoon-googleplus"></i></a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <div class="team-member animated" data-animation="fadeIn">
              <div class="avatar-team"> <img alt="img"   src="/assets/media/team/2.png"></div>
              <div class="details-team">
                <h3 class="heading">Mark Deo</h3>
                <h4 class="sub-heading">CO-OWNER</h4>
                <div class="desc-det"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's .
                  <section class="progress-section">
                    <div class="level-skill">Skill Level:</div>
                    <div class="progress-bar">
                      <div class="progress"></div>
                    </div>
                  </section>
                </div>
                <ul class="unstyled clearfix social-team">
                  <li><a  target="_blank" href="http://fb.com/#"><i class="icomoon-facebook"></i></a></li>
                  <li><a target="_blank" href="http://twitter.com/#"><i class="icomoon-twitter"></i></a></li>
                  <li><a target="_blank"  href="http://plus.google.com/#"><i class="icomoon-googleplus"></i></a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <div class="team-member animated" data-animation="fadeIn">
              <div class="avatar-team"> <img alt="img"   src="/assets/media/team/3.png"></div>
              <div class="details-team">
                <h3 class="heading">Jessica Smith</h3>
                <h4 class="sub-heading">BROKER</h4>
                <div class="desc-det"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's .
                  <section class="progress-section">
                    <div class="level-skill">Skill Level:</div>
                    <div class="progress-bar">
                      <div class="progress"></div>
                    </div>
                  </section>
                </div>
                <ul class="unstyled clearfix social-team">
                  <li><a  target="_blank" href="http://fb.com/#"><i class="icomoon-facebook"></i></a></li>
                  <li><a target="_blank" href="http://twitter.com/#"><i class="icomoon-twitter"></i></a></li>
                  <li><a target="_blank"  href="http://plus.google.com/#"><i class="icomoon-googleplus"></i></a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <div class="team-member animated" data-animation="fadeIn">
              <div class="avatar-team"> <img alt="img"   src="/assets/media/team/4.png"></div>
              <div class="details-team">
                <h3 class="heading">Stepan Deo</h3>
                <h4 class="sub-heading">MARKETER</h4>
                <div class="desc-det"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's .
                  <section class="progress-section">
                    <div class="level-skill">Skill Level:</div>
                    <div class="progress-bar">
                      <div class="progress"></div>
                    </div>
                  </section>
                </div>
                <ul class="unstyled clearfix social-team">
                  <li><a  target="_blank" href="http://fb.com/#"><i class="icomoon-facebook"></i></a></li>
                  <li><a target="_blank" href="http://twitter.com/#"><i class="icomoon-twitter"></i></a></li>
                  <li><a target="_blank"  href="http://plus.google.com/#"><i class="icomoon-googleplus"></i></a></li>
                </ul>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="portfolio-navigation"> <a href="javascript:void(0);" class="btn btn-primary slider-direction prev-page disabled"><i class="icomoon-arrow-left2"></i></a> <a href="javascript:void(0);" class="btn btn-primary slider-direction next-page"><i class="icomoon-arrow-right2"></i></a>
        <ul class="pages unstyled">
          <li class="active">1</li>
          <li>2</li>
          <li>3</li>
          <li>4</li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!-- // OUR TEAM SECTION -->


<!-- WE DEAL IN LARGE NUMBER OF VEHICLES -->
<section id="facts" class="section section-bg"  style="background-image:url(/assets/media/numbers/bg.png); display:none" >
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-9">
        <header class="section-header-simple">
          <div class="heading-wrap">
            <h2 class="heading"> <span>WE DEAL IN LARGE NUMBER OF VEHICLES</span></h2>
          </div>
          <p> Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum  Vivamuslobo rtis consequat purus. Curabitur commodo.
            Eltiam sed nulla. Lorem ipsum dolor sit met conse clt etuer adipiscing elit Nulla libero. </p>
        </header>
      </div>
    </div>
    <div class="row text-center animated" data-animation="bounceIn"> 
      <script src="/assets/js/jquery.easing.1.3.js"></script> 
      <script src="/assets/js/jquery.easypiechart.js"></script> 
      
      <!-- BEGIN -->
      <div class="col-xs-12 col-sm-12 col-lg-12">
        <article data-animation="fadeInDown" class="numbers clearfix animated text-left  fadeInDown">
          <ul>
            <li>
              <div class="overflow-offer"> <a href="#" class="wrap-offer"> <i class="auto12"></i>
                <p class="offer-name">SCOOTERS & BIKES</p>
                </a> </div>
              <span class="span-title"><span class="chart" data-percent="99"> <span class="percent"></span> </span> OFFERS</span> </li>
            <li>
              <div class="overflow-offer"> <a href="#" class="wrap-offer"> <i class="auto13"></i>
                <p class="offer-name">SCOOTERS & BIKES</p>
                </a></div>
              <span class="span-title"><span class="chart" data-percent="96"> <span class="percent"></span> </span> OFFERS</span></li>
            <li>
              <div class="overflow-offer"><a href="#" class="wrap-offer"> <i class="auto14"></i>
                <p class="offer-name">SCOOTERS & BIKES</p>
                </a> </div>
              <span class="span-title"><span class="chart" data-percent="89"> <span class="percent"></span> </span> OFFERS</span></li>
            <li>
              <div class="overflow-offer"><a href="#" class="wrap-offer"> <i class="auto15"></i>
                <p class="offer-name">SCOOTERS & BIKES</p>
                </a> </div>
              <span class="span-title"><span class="chart" data-percent="86"> <span class="percent"></span> </span> OFFERS</span></li>
            <li>
              <div class="overflow-offer"> <a href="#" class="wrap-offer"> <i class="auto16"></i>
                <p class="offer-name">SCOOTERS & BIKES</p>
                </a></div>
              <span class="span-title"><span class="chart" data-percent="54"> <span class="percent"></span> </span> OFFERS</span></li>
          </ul>
        </article>
      </div>
      
      <!-- END --> 
    </div>
  </div>
</section>



<!-- REVIEWS SECTION-->
<section class="section section-white" id="our-reviews" style="display:none">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
      
         <header class="section-header">
          <div class=" animated" data-animation="bounceInLeft"> <i class="autologo_avto"></i> </div>
          <div class="heading-wrap">
            <h2 class="heading " ><span>OUR Reviews</span></h2>
          </div>
        </header>
        
        
        
      </div>
    </div>
  </div>
  <div class="container">
    <div  class="row text-center">
      <div class="reviews-frame " >
        <ul class="review-slider" >
          <li>
            <div data-animation="fadeIn" class="team-member animated  fadeIn">
              <div class="avatar-review"> <img src="/assets/media/team/1.png" alt="img"></div>
              <div class="details-review">
                <div class="desc-det"> Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum muslobortis consequat purus. Duis viverra malesuada mi. Fusce ante augue, convallis sit am
                  et volutpat ac, posuere vel, quam. </div>
                <div class="review-autor">
                  <h3 class="heading">John Deo</h3>
                  <h4 class="sub-heading">CAR OWNER</h4>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div data-animation="fadeIn" class="team-member animated  fadeIn">
              <div class="avatar-review"> <img src="/assets/media/team/2.png" alt="img"></div>
              <div class="details-review">
                <div class="desc-det"> Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum muslobortis consequat purus. Duis viverra malesuada mi. Fusce ante augue, convallis sit am
                  et volutpat ac, posuere vel, quam. </div>
                <div class="review-autor">
                  <h3 class="heading">John Deo</h3>
                  <h4 class="sub-heading">CAR OWNER</h4>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div data-animation="fadeIn" class="team-member animated  fadeIn">
              <div class="avatar-review"> <img src="/assets/media/team/2.png" alt="img"></div>
              <div class="details-review">
                <div class="desc-det"> Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum muslobortis consequat purus. Duis viverra malesuada mi. Fusce ante augue, convallis sit am
                  et volutpat ac, posuere vel, quam. </div>
                <div class="review-autor">
                  <h3 class="heading">Mark Deo</h3>
                  <h4 class="sub-heading">CAR OWNER</h4>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div data-animation="fadeIn" class="team-member animated  fadeIn">
              <div class="avatar-review"> <img src="/assets/media/team/4.png" alt="img"></div>
              <div class="details-review">
                <div class="desc-det"> Phasellus imperdiet libero sit amet ante. Donec convallis elementum leo. Cum muslobortis consequat purus. Duis viverra malesuada mi. Fusce ante augue, convallis sit am
                  et volutpat ac, posuere vel, quam. </div>
                <div class="review-autor">
                  <h3 class="heading">Jessica Smith</h3>
                  <h4 class="sub-heading">CAR OWNER</h4>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="portfolio-navigation"> <a class="btn btn-primary slider-direction prev-page disabled" href="javascript:void(0);"><i class="icomoon-arrow-left2"></i></a> <a class="btn btn-primary slider-direction next-page" href="javascript:void(0);"><i class="icomoon-arrow-right2"></i></a>
        <ul class="pages unstyled">
          <li class="active">1</li>
          <li>2</li>
          <li>3</li>
          <li>4</li>
        </ul>
      </div>
    </div>
  </div>
</section>



<!-- BRAND -->
<section id="our-clients" class="section" style="background:#f4f4f4; display:none;" >
  <div class="container">
    <div class="row ">
      <div class="col-md-offset-3 col-md-6">
        <header class="section-header section-header-type2">
          <div class="heading-wrap">
            <h2 class="heading heading-type2"><span>POPULAR BRANDS</span></h2>
          </div>
        </header>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row  " >
      <table >
        <tr class="first">
          <td class="first"><a href="#" ><img alt="img"   src="/assets/media/brands/1.png" ></a></td>
          <td><a href="#"><img alt="img"   src="/assets/media/brands/2.png" ></a></td>
          <td><a href="#"><img alt="img"   src="/assets/media/brands/3.png" ></a></td>
          <td><a href="#"><img alt="img"   src="/assets/media/brands/4.png" ></a></td>
 
        </tr>
      </table>
    </div>
  </div>
</section>


<!-- CONTACT US SECTION -->
<section  class="section section-white"  id="contact" style="display:none" >
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
      
         <header class="section-header">
          <div class=" animated" data-animation="bounceInLeft"> <i class="autologo_avto"></i> </div>
          <div class="heading-wrap">
            <h2 class="heading " ><span>Contacts Us</span></h2>
          </div>
           <p>Vestibulum fringilla nulla ultricies sem. Phasellus sit amet lorem at odio Nulla pede duislw</p>
        </header>
        
        
       
        
        
      </div>
    </div>
    <div class="row contact-row">
      <div class="col-xs-12 col-sm-12 col-lg-6">
        <h4>SEND US AN INQUIRY</h4>
        <form id="contact-form"  class="form-full-width contact-form">
          <div class="row">
            <div class="col-xs-12 col-sm-12">
              <div class="form-group">
                <input placeholder="YOUR NAME*" type="text" id="contact-subject1" name="subject" />
              </div>
            </div>
            <div class="col-xs-12 col-sm-12">
              <div class="form-group">
                <input placeholder="PHONE*" type="text" id="contact-subject2" name="subject" />
              </div>
            </div>
            <div class="col-xs-12 col-sm-12">
              <div class="form-group">
                <input placeholder="SUBJECT*" type="text" id="contact-subject3" name="subject" />
              </div>
            </div>
            <div class="col-xs-12 col-sm-12">
              <div class="form-group">
                <textarea placeholder="YOUR MESSAGE*" id="contact-message" name="message" ></textarea>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 text-left">
              <div class="wrap-main">
                <button id="contact-submit" class="btn btn-main btn-primary btn-lg uppercase"><span>Send Message</span></button>
              </div>
            </div>
          </div>
        </form>
        
        <!-- /CONTACT FORM ALERTS --> 
        
      </div>
      <div class="col-xs-12 col-sm-12 col-lg-6 pull-right contact-text">
        <h4>AUTOIMAGE AUTO DEALERS</h4>
        <p>Address: Street No. 123, Main Road, City Name, IL 33025<br>
          Phone: 555 666 777<br>
          Fax: +1 23 4567 899<br>
          Email: <a href="mailto:info@delicategem.com">info@autoimage.com</a></p>
        <p>&nbsp; </p>
        <h4>WORKING HOURS</h4>
        <p>Monday to Friday: 9 A.M. to 6 P.M.<br>
          Saturday: 9 A.M. to 1 P.M.<br>
          No working hours on Sunday </p>
        <p>&nbsp; </p>
        <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a> <a href="#"><i class="fa fa-html5"></i></a> <a href="#"><i class="fa fa-youtube"></i></a> <a href="#"><i class="fa fa-flickr"></i></a> <a href="#"><i class="fa fa-vk"></i></a> </div>
    </div>
  </div>
  <div class="map">
    <iframe src="https://maps.google.com/?ie=UTF8&amp;ll=38.85682,-103.996582&amp;spn=7.304424,16.907959&amp;t=m&amp;z=7&amp;output=embed" class="iframe" ></iframe>
  </div>
</section>
<!-- // CONTACT US SECTION --> 



   <?php echo $this->render('_footer.phtml'); ?>
    
  