<script type="text/javascript">
$(document).ready(function() {

    var oTable = $("#gallery_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->adminUrl('list-gallery-data', 'gallery') ?>",
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            { "bSortable": true, sWidth: '50px' },
            null,
            { "bSortable": false, sWidth: '150px' }
        ]
    }).yadcf([
	{column_number : 0, filter_type: "text"},
	{column_number : 1, filter_type: "text"}
    ]);

    $("#gallery_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });

});
</script> 

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil-2"></span>
                    <span><?php echo $this->translate('Galeria') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-gallery', 'gallery') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
                </h4>
                
            </div>
            <div class="content clearfix">

                <table id="gallery_table" cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" width="100%">
                    <thead>
			<tr>
			    <th><?php echo $this->translate('Id') ?></th>
			    <th><?php echo $this->translate('Name') ?></th>
			    <th><?php echo $this->translate('Options') ?></th>
			</tr>
			<tr>
			    <th><?php echo $this->translate('Id') ?></th>
			    <th><?php echo $this->translate('Name') ?></th>
			    <th><?php echo $this->translate('Options') ?></th>
			</tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            
            </div>

        </div><!-- End .box -->

    </div>

</div>
