<section class="page_title translucent_bg_color_scheme image_fixed t_align_c relative wrapper" style="background: url('/media/photos/1645854905/1680x380/cropped-banner-2.jpg');">
    <div class="container">
        <h1 class="color_light fw_light m_bottom_5">
            <?php echo $this->page['Translation'][$this->language]['name']; ?>
        </h1>
        <!--breadcrumbs-->
        <ul class="hr_list d_inline_m breadcrumbs">
            <li class="m_right_8 f_xs_none">
                <a href="<?php echo $this->url(array(), 'domain-i18n:homepage') ?>" class="color_grey_light_3 d_inline_m m_right_10">Home</a>
                <i class="icon-angle-right d_inline_m color_grey_light_3 fs_small"></i>
            </li>
            <li>                </li>
	    <li>
		<a class="color_grey_light_3 d_inline_m m_right_10" href="javascript:void(0)">
                           <?php echo $this->page['Translation'][$this->language]['name']; ?>                          
                    </a>
	    </li>
	</ul>
    </div>
</section>
<section class="section_offset page">
	<main class="container t_align_c">
		<h3 class="color_dark fw_light m_bottom_15 heading_1"><?php echo $this->page['Translation'][$this->language]['name']; ?></h3>
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 m_xs_bottom_20">
				<img src="/media/photos/<?php echo $this->page['PhotoRoot']['offset']; ?>/<?php echo $this->page['PhotoRoot']['filename']; ?>" class="r_corners" alt="">
			</div>
			<div class="col-lg-6 col-md-6 t_align_l">
			    <?php echo $this->page['Translation'][$this->language]['description']; ?>
			</div>
		</div>
	</main>
</section>